### ISSUE TITLE
bug: degrees axis seems to be wrong

### ISSUE THREAD

**Issue by michaelschf1** [Emigon/qutilities#1]
By running this piece of code I got weirdly small phase scale in degrees. I expected it to be in the order of 180 or 360 deg phase shift at resonance.

That`s actually .py file, so rename to .py:
[qutils_analise.txt](https://github.com/Emigon/qutilities/files/4095094/qutils_analise.txt)

Result:
![deg_wrong](https://user-images.githubusercontent.com/32321209/72862166-5d319600-3d20-11ea-8c47-2e5a3f693328.png)

Data used, that`s actually pickles, so rename to .pkl
[mag_PinRES_n120_0.5_0.55kGauss.txt](https://github.com/Emigon/qutilities/files/4095099/mag_PinRES_n120_0.5_0.55kGauss.txt)
[phi_PinRES_n120_0.5_0.55kGauss.txt](https://github.com/Emigon/qutilities/files/4095100/phi_PinRES_n120_0.5_0.55kGauss.txt)

**Comment by Emigon** [comment]
Fixed in fitkit: commit 254d1c9. Closing.
